### PR TITLE
transition component adjustments

### PR DESCRIPTION
**Pull request by michelengelen**
added several new features to the transition component

- possibility to add different values for in/out duration and delay
- added possibility to use custom transitions
- changed the way transitions are applied to the css
- changed typing and structure of transition definition
- added props documentation

### CODE REVIEW

**Review by nevyangelova — COMMENTED** [review]
IMO we should approach this slightly differently. I like how you specified the exact transitions we would have and not adding the option for a custom transition. That way we can have a strict and unified set of transitions we would use, and we don’t need to add additional types and custom transition specific logic in our Styled component. What do you think ?

**Comment by michelengelen** [comment]
> IMO we should approach this slightly differently. I like how you specified the exact transitions we would have and not adding the option for a custom transition. That way we can have a strict and unified set of transitions we would use, and we don’t need to add additional types and custom transition specific logic in our Styled component. What do you think ?

I dont know if I got what you intended to convey.
DId you propose to remove the functionality to add a custom transition and only define those we want to have?

**Comment by nevyangelova** [comment]
> > IMO we should approach this slightly differently. I like how you specified the exact transitions we would have and not adding the option for a custom transition. That way we can have a strict and unified set of transitions we would use, and we don’t need to add additional types and custom transition specific logic in our Styled component. What do you think ?
> 
> I dont know if I got what you intended to convey.
> DId you propose to remove the functionality to add a custom transition and only define those we want to have?

Genau!

**Comment by michelengelen** [comment]
> > > IMO we should approach this slightly differently. I like how you specified the exact transitions we would have and not adding the option for a custom transition. That way we can have a strict and unified set of transitions we would use, and we don’t need to add additional types and custom transition specific logic in our Styled component. What do you think ?
> > 
> > 
> > I dont know if I got what you intended to convey.
> > DId you propose to remove the functionality to add a custom transition and only define those we want to have?
> 
> Genau!

the problem is, that special transitions would be made impossible (e.g. color transitions) ... IMO we should leave it like that for now.

WDYT @deanwhillier ? I would like to hear your opinion on this as well.

**Review by nevyangelova — APPROVED** [review]

**Comment by michelengelen** [comment]
gentle reminder to review @deanwhillier

**Comment by deanwhillier** [comment]
@michelengelen, can you please point me to a use case for the transition component and/or relevant discussions I may have missed while out? Have you implemented it anywhere yet? I'm interested in understanding what we are trying to solve with this and how.

Also, wondering if you could please move non-relevant component tweaks/updates to a separate PR to keep the focus of this PR on the transition component and specific use cases if any.

**Comment by nevyangelova** [comment]
> @michelengelen, can you please point me to a use case for the transition component and/or relevant discussions I may have missed while out? Have you implemented it anywhere yet? I'm interested in understanding what we are trying to solve with this and how.
> 
> Also, wondering if you could please move non-relevant component tweaks/updates to a separate PR to keep the focus of this PR on the transition component and specific use cases if any.

This was introduced firstly as a helper for the popover transition, we were discussing if its possible to unify the checkbox, radio and switch transition as well, as they are kinda similar in their HTML structure but we didn't reach a concrete answer yet as we aren't sure if this is the best approach yet. The idea was to have something like input helper components and one would be the input itself with transition, the other would be the label. But its still something that needs to be discussed.

**Comment by michelengelen** [comment]
> @michelengelen, can you please point me to a use case for the transition component and/or relevant discussions I may have missed while out? Have you implemented it anywhere yet? I'm interested in understanding what we are trying to solve with this and how.

@nevyangelova already answered this one. It is basically an attempt to unify transitions wherever possible. It makes sense in "entry-transitions", every form of size manipulations and such, but not so much for others (e.g. hover-states).

> Also, wondering if you could please move non-relevant component tweaks/updates to a separate PR to keep the focus of this PR on the transition component and specific use cases if any.

Yeah, @nevyangelova already yelled at me for that as well! SRY! ... I promise I will keep that in mind! 🙇🏼‍♂️

**Comment by nevyangelova** [comment]
yes, sorry to butt in here 🙈

**Review by nevyangelova — APPROVED** [review]

**Pull request merged**
