### PR TITLE
Feature - User-/Team-Avatar

### PR DESCRIPTION
**Pull request by michelengelen**
#### Summary
adds UserAvatar and TeamAvatar components

#### Ticket Link
Fixes [MM-33453](https://mattermost.atlassian.net/browse/MM-33453) and [MM-33455](https://mattermost.atlassian.net/browse/MM-33455)

### CODE REVIEW

**Review by nevyangelova — DISMISSED** [review]
Lgtm, minus replacing with the image component 🙏🏻

**Comment by michelengelen** [comment]
@nevyangelova could you please re-review? Thanks! ✨

**Review by nevyangelova — APPROVED** [review]
LGTM

**Pull request merged**
